### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by pstavirs** [openaustralia/morph#565]
I'm encountering a SSL certificate error consistently in my scraper - https://morph.io/pstavirs/BinTrayDownloadStatistics

Is there a SSL certificate problem? I don't see the problem when I run the scraper locally on my machine or when I access the same url via the browser.

Traceback (most recent call last):
  File "/repo/scraper.py", line 15, in <module>
    page = requests.get('https://bintray.com/statistics/packageStatistics?pkgPath=/pstavirs/ostinato/'+package)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 269, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 364, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 163, in send
    raise SSLError(e)
requests.exceptions.SSLError : [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by mlandauer** [comment]
It looks like the python requests library gets its local CA certificates in a different way to other python libraries. I should be able to fix this so that it all works transparently. Working on a fix now.

**Comment by mlandauer** [comment]
Hi @pstavirs - thanks so much for reporting the problem. It should all be fixed now and the next time you run your scraper it should all just work again. Sorry for the hassle! If you find any other problems don't hesitate to put in another ticket. Thanks again!

**Comment by pstavirs** [comment]
Looks like the problem is back (same scraper, same error) -
Injecting configuration and compiling...
Injecting scraper and running...
Last date in DB: 2015-06-09
Traceback (most recent call last):
  File "scraper.py", line 15, in <module>
    page = requests.get('https://bintray.com/statistics/packageStatistics?pkgPath=/pstavirs/ostinato/'+package)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 269, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 364, in send
    r = adapter.send(request, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/adapters.py", line 163, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
